### ISSUE TITLE
재고 수정 기능

### ISSUE THREAD

**Issue by chanwooDev** [woowa-camp-2023-4/backend#10]
재고 id를 기반으로 등록된 재고의 수량, 유통기한을 수정할 수 있다.

판매자가 재고를 보충할 경우 수량 추가 업데이트할 수 있으며 그렇다면 품절상태는 해제가 되고 사용자는 수량만큼의 구매를 할 수 있다.

품절상태가 아니더라도 보충을 할 수 있으며 원하는 개수를 추가한다

유통기한이 다른 상품이 보충될 수 있다.

재고 불량시 수량이 수정될 수 있다

**Comment by chanwooDev** [comment]
@bkRyusim

**Comment by impati** [comment]
우선순위에 밀려 close
