### ISSUE TITLE
관리자는 상품 판매 상태를 수정할 수 있다.

### ISSUE THREAD

**Issue by bkRyusim** [woowa-camp-2023-4/backend#23]
상품의 판매 상태를 수정할 수 있다.
상품이 상태는 다음과 같다.

### Target State가 될 수 있는 상태
- [X] `판매 중` : 조회 시 정상적으로 노출될 수 있는 상태.
  - 재고가 0인 상태에는 `판매 중`으로 변경할 수 없다.
- [X] `판매 종료` : 조회 시 노출되지 않는 상태
  - 이전 상태에 관계없이 설정할 수 있다.

### Target State가 될 수 없는 상태
-  [x] #51
    - 재고가 하나도 없는 경우 자동으로 품절 상품으로 처리한다.
- [X] `가등록` : 처음 상품이 생성되었을 때의 상태.
  - 최초 생성시에만 할당할 수 있는 상태
  - 최초 생성시 자동 할당된다

**Comment by impati** [comment]
**상품 재고가 0이 되는 경우 구매하는 쪽에서 상품 상태를 품절 상태로 변경해야한다.**

**Comment by impati** [comment]
PR #60  에서  해결
