### ISSUE TITLE
상품 상세 내용(밀키트)를 관리하는 기능

### ISSUE THREAD

**Issue by bkRyusim** [woowa-camp-2023-4/backend#27]
#14 로부터 분기
밀키트 도메인에 특화된 요소들을 다룰 소 있는 DB 구조 설계 및 엔티티 매핑 필요

ProductDetail
- 포장 타입 (`냉장`, `냉동`)
- 카테고리
- 브랜드
- 중량 정보
- 판매 단위??
- 원산지
- 알레르기 정보
- 상품 상태 
- 상품의 최대 구매 가능 수량

**Comment by impati** [comment]
우선순위에 밀려 close
