### ISSUE TITLE
상품 상태 변경 관련 엔드포인트 설계

### ISSUE THREAD

**Issue by bkRyusim** [woowa-camp-2023-4/backend#43]
#22 수행 중 엔드포인트 설계에 관한 내용입니다.

현재 아래와 같이 PATCH 메서드를 이용해 Status를 수정하는 방식으로 상품 상태를 변경합니다.
```
PATCH  /products/{productId}/status

{
   "productStatus" : "IN_STOCK"
}
```

이렇게 될 경우, `상품 판매 시작`, `상품 판매 중단`이라는 두 가지 행위가 단일 엔드포인트를 통해 수행되고,
각각의 행위에 도메인 정책이 더해질수록 updateStatus 메서드 내 분기가 길어지고 유지보수가 힘들어진다는 단점이 있습니다.

예를 들어, **상품 판매 시작 시 관심상품에 등록한 사용자에게 푸시 알림을 보낸다** 등, 판매 시작이라는 행위에 따라오는 부수적인 동작이 붙을수록 현재 구조로는 코드가 더러워질 것 같습니다.

아래와 같이 두 개의 POST 요청으로 나누는 것을 생각해 볼 수 있겠네요

```
POST /products/{productId}/launch
POST /products/{productId}/suspend
```

다만 상품의 상태가 많아지면 그만큼 엔드포인트도 많아진다는 단점이 있습니다.
추후 현재 상태로 문제가 발생하면 그 때 다시 논의하면 될 것 같습니다.

**Comment by impati** [comment]
현재까지는 적합하다고 판단 [Discussion](https://github.com/woowa-camp-2023-4/backend/discussions/121) 에서 추후 논의
