### ISSUE TITLE
fix: 재고 추가 로직에 동일한 유통기한에 대해서 수량을 증가시켜야함

### ISSUE THREAD

**Issue by chanwooDev** [woowa-camp-2023-4/backend#92]
현재 동일한 날짜에 대한 수량 등록을 하면 새로운 row가 발생하고 수량이 합해지지 않음
<img width="716" alt="스크린샷 2023-08-25 오전 10 12 06" src="https://github.com/woowa-camp-2023-4/backend/assets/39613774/9ac2be96-9f38-4354-80df-73b0cd7c2b01">

**Comment by impati** [comment]
alter table stocks add constraint uq_stock unique(product_id , expiry_date);
